# Generated by Django 3.0.1 on 2021-02-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0002_auto_20210228_1609'),
    ]

    operations = [
    ]
